[package]
name = "minlisp"
version = "0.1.0"
authors = ["hman523 <shbarbella@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "1.9"
rustyline = "5.0.4"
